* TODO Use RefTeX's ~reftex-section-regexp~ to recognize arbitrary LaTeX sectioning commands
- [[elisp:(load-library "reftex")][ ~(load-library "reftex")~ # before clicking the function link]]
- [[help:reftex-section-regexp][reftex-section-regexp]]
- navigate to the ~setq~ for that symbol.

* TODO Write a GitHub workflow for generating the PDF, Emacs Package, and running elisp tests
- DONE when the .workflow is tested and adopted
- Primarily useful for the PDF
  - Using a container increases reproducibility; [[https://github.com/xu-cheng/texlive-action][this existing latex workflow on GitHub actions]] is sufficient

#+begin_src yaml
  on: [release]
  jobs:
    build_latex:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: xu-cheng/texlive-action@v3
          with:
            texlive_version: 2020
            os: debian
            run: |
              - "markup -Rwhyse.el | autodefs.elisp | finduses.elisp | clean-docs | noidx -delay > whyse.tex"
              - "latexmk -pdf -file-line-error -halt-on-error -interaction=nonstopmode whyse.tex"
#+end_src

* DONE Hack on the recognizer.nw and finduses.nw to better support (Emacs) LISP
CLOSED: [2025-07-25 Fri 01:17]
Find Uses and the Recognizer (respectively in =finduses.nw= and =recognizer.nw=)
need some tweaking to better support LISP identifiers. It may be as simple as
moving =-= from ~SYMBOLS~ to ~ALPHANUMERIC~.

* TODO Improve the parse tree, per the FIXME in =test/test-parser-with-temporary-buffer.el=
The current parse tree contains a ~nil~ after the chunk type and number assoc,
and that needs to be analyzed. Why is this ~nil~ in the stack? I assume and
believe it is because of the collapsing of stringy tokens; when a token should
be put back onto the stack it may also be putting a ~nil~ onto the stack in the
first call to the function.

* TODO Improve documentation of the default hook
Better document the functionality of the default hook function
~w--prepare-sexp-sql-from-file-tokens~. The current explanation is a copy of the
brief explanation in the hook documentation string.

* Prosaic improvements
- [[file:src/whyse.nw::simple. It is defined quickly, then explained briefly.][Ensure that the previous statement in-prose [not in the TODO summary] is still correct.]]
- [[file:src/whyse.nw::to summarize: \[\[w-open-project-hook\]\] is run.][Describe initialization of the system after parsing.]]
- [[file:src/whyse.nw::Every project should have a database file located somewhere within the][Finish the creation of a database. Use what I learned in the fall!]]
- [[file:src/whyse.nw::Sometimes, however, the system will permit a chunk to be undefined and][Verify that this statement is true]]: ``Usually Noweb will warn a user that a chunk was referenced but undefined, or that there was some other issue with chunks.''
- [[file:src/whyse.nw::<<functions to collapse text and newline tokens into their largest possible form>>][Place the insertion of the functions into the code chunk better.]]
- [[file:src/whyse.nw::featureset of SQL). The history of SEQL statements compiled is treated like a][Make the number of entries in this history list]] customizable, limited to some given number or a default of one hundred.
- [[https://www.gnu.org/software/emacs/manual/html_node/ert/][Adopt the ERT (Emacs Regression Tests)]] package

  To test WHYSE features as they are developed and become featureful. When a
  feature is implemented a test should be written which conforms to the
  current documentation so that regressions can be caught when changes are
  made.
- [[https://github.com/alphapapa/makem.sh][Adopt/use makem.sh]], by ``alphapapa''.

* Explore alternative implementations
An implementation of something WHS-like in Org mode, rather than noweb-mode,
would be interesting. It seems quite capable, and in fact is more featureful
than noweb. Noweb may be outmoded, honestly, but it does have its place.

** TODO Buttonizing all =<<noweb chunk headers>>== in poly-noweb mode buffers
Rather than using widget.el in the main Polymode buffer it would be prudent to
use the Button package to make buttons out of pre-existing text.

There are utilities for mapping over all "spans" in a polymode buffer, e.g.
[[help:pm-map-over-spans][polymode map over spans]].

#+begin_quote markdown
`:head-mode` and `:tail-mode` specify the major mode which should be used for
head and tail respectively. Special symbol `'host` means that the host mode is
used for head or tail, if `'body` [then] the mode of the chunk's body. Head and
tail modes default to `poly-head-tail-mode` which is a very basic prog mode with
no special powers.
#+end_quote

I need to define a mode. The mode must have a keymap to navigate chunks:
preferrably a transient map or hydra like Info mode.

#+begin_src elisp :noweb yes :tangle noweb-navigation-mode.el
  (define-minor-mode nwn-mode
    "Noweb Narrowing minor mode provides alternative motion commands
            between pages, defined by a buffer-local value of
            `page-delimiter' appropriate for Noweb chunks."
    :lighter " nWn "
    :list '(fundamental-mode text-mode latex-mode noweb-mode poly-noweb-mode)
    :keymap '(([next] . nwn--forward-page)
              ([prior] . nwn--backward-page))
    (if <<current buffer is a noweb file>>
        (if nwn-mode
            (progn (make-local-variable 'page-delimiter)
                   <<customize page-delimiter regular expression for noweb>>
                   (nwn-narrow-to-page))
          (kill-local-variable 'page-delimiter)
          (when (buffer-narrowed-p)
            (widen)))
        (message "Current buffer is not a noweb file; refusing to enable nwn-mode!")))

  (define-child-mode noweb-navigation-mode text-mode)
  (defun noweb-navigation-mode (&rest mode-arguments)
    "\[COMMAND] is exclusively for use as a :head-mode and :tail-mode with poly-noweb. It has no other purpose.

  \{KEYMAP}

  \<KEYMAP>"

    (kill-all-local-variables)
    (set-variable 'major-mode noweb-navigation-mode)
    (use-local-map
     (let ((map (make-sparse-keymap)))
       ;; TODO: these dwim functions should be cyclic. Once at the last definition
       ;; of a chunk continuing to the next should return the user to the first
       ;; definition of the chunk.
       (define-key map "n" #'next-noweb-chunk-definition-dwim)
       (define-key map "p" #'previous-noweb-chunk-definition-dwim)

       ;; TODO: these dwim functions should cycle through the next visible
       ;; defintions of a chunk which is the sibling of the currently visited
       ;; chunk.
       (define-key map "S-n" #'next-noweb-chunk-sibling-definition-dwim)
       (define-key map "S-p" #'previous-noweb-chunk-sibling-definition-dwim)

       ;; TODO: these dwim functions should cycle through parents of the currently
       ;; visited chunk.
       (define-key map "M-n" #'next-noweb-chunk-parent-definition-dwim)
       (define-key map "M-p" #'previous-noweb-chunk-parent-definition-dwim)
       map)))
#+end_src

* Tangle the README from this org file rather than from a noweb file.
The README file is tangled with the following chunks in the order given.

#+begin_src markdown :noweb yes :tangle README.md
  <<about>>

  <<development>>

  <<latex>>

  <<hiatus>>

  <<directory>>
#+end_src

I need to tell first-time visitors what WHYSE is, and why they might like to use it.

For those interested in using it they need to know how to download and install
it; it is not my purpose to teach them how to use GitHub. There's a big green
button, if a visitor cannot press that they won't be able to use WHYSE
regardless.

As an Emacs mode it doesn't require LaTeX or make on the user's system. As a
literate document this is required.

#+begin_src markdown :noweb-ref latex
  ## LaTeX compilation difficulties
  I have not had success compiling a knoweb-styled LaTeX document in any environment apart from a
  Debian 11 OS environment with TeXLive 2020. Only this combination works; other
  versions of TexLive or newer versions of Debian, or other Linux distributions
  have not worked with the peculiarities of the style file and the latex
  environment.

  As of Saturday, July 26 2025 there is now a Dockerfile which I successfully use
  with `podman` on my Fedora Silverblue machine to build whyse and all of its
  dependencies.
#+end_src

#+begin_src markdown :noweb-ref about
  # About
  The WEB Hypertext System[^2] implemented in Emacs Lisp for Norman Ramsey's Noweb[^1] rather than Knuth's Pascal-based WEB or the later CWEB.

  [^1]: Ramsey, Norman. Literate Programming Simplified. IEEE Software, 11(5):97–105, September 1994

  [^2]: Brown, M. and Bogdan D. Czejdo. “A Hypertext for Literate Programming.” International Conference on Computing and Information (1991)

  # WHYSE ⸺ The WEB HYpertext System in Emacs
  WHYSE is an integrated development environment for Noweb and LaTeX,
  integrating these tools with new system features for editing and reviewing literate programs.

  The IDE is inspired by the system described in Brown and Czejdo's 1991 ICCI
  conference proceeding, and is in early development.
#+end_src

#+begin_src markdown :noweb-ref hiatus
  # Returning to development after a long hiatus
  One of the hallmarks of literate programming is the supposed speed with which a
  developer can acquaint (or re-acquaint) themselves with a codebase. The
  suppository is that you're directly inputting the source code whilst reading
  copius documentation explaining the reasoning for that code and the way it fits
  together with other parts while you're construting your own mental model (while
  you are reading critically, because all software and documentation has errors
  and omissions).

  I'm returning to the project on April 19th, 2025 (Sat 19 Apr 2025 12:34:49 AM
  MDT). I am not sure how long I have been away; after checking the git log it
  appears I've been largely inactive since May 13th, 2024. That's nearly one year!

  I was inactive after the last "return" until late-July 2025. Significant
  progress was made in terms of the Dockerfile.
#+end_src

#+begin_src markdown :noweb-ref directory
  # Ignored files
  If you've received a tarball of this source code you may have received
  additional files which are otherwise ignored. One of these is whs.pdf,
  which is a rendering of the source code from an earlier version of
  whyse retained only to show what a PDF should look like.
#+end_src

** TODO update the file tree in the following chunk (it is out of date)

#+begin_src markdown :noweb-ref development
  # Development overview
  To orient new contributors and help adventurous hackers use the software, this
  overview is provided to help with navigation.

  Firstly, Noweb 2.13 and LaTeX are required for development. Run `make
  compile-pdf` to compile and render the PDF on your system.

  The files /I have in my directory/ are as follows.

  ```
  ~/Documents/src/whyse $ tree
  .
  ├── build
  │   ├── artifacts
  │   └── whyse-0.1.tar
  ├── LICENSE
  ├── Makefile
  ├── README.md
  ├── src
  │   ├── clean-docs.awk
  │   ├── offsets.awk
  │   ├── README.nw
  │   ├── whyse.bib
  │   └── whyse.nw
  ├── test
  │   ├── makem.sh
  │   ├── test-parser-with-temporary-buffer.el
  │   └── widgetry.el
  ├── TODO.org
  └── vendor
      ├── autodefs.elisp
      ├── gpl-3.0.tex
      ├── knoweb.el
      ├── knoweb.sty
      └── noweb.sty

  6 directories, 18 files
  ```

  `autodefs.elisp` and `knoweb.sty` are taken from the knoweb project, which
  provides LaTeX support for Noweb and Emacs Lisp identifier definitions in AWK
  for Noweb to use for indexing. Upstream knoweb is not required.

  The *project* license is contained in `LICENSE`. Particular files, if released
  under a different license, contian separate licensing notices where appropriate
  within the file; binary files do not contain license notices, and images, fonts,
  sounds, movies, etc. are under their own license, if any works of these mediums
  exist within the project at any time.

  The Makefile has commands to `weave` Noweb to LaTeX source, `tangle` files from
  Noweb sources, and `compile-pdf`s from generated LaTeX sources. It also
  contains a command to generate Noweb intermediate tool syntax for developer
  inspection.

  `whyse.bib` contains a BibTeX reference for academic works. Of note, it contains
  a reference to Brown & Czejdo's 1991 paper that inspired this package.

  The only other source file is `whyse.nw`, the Noweb source for WHYSE itself.

#+end_src

