name: Build Whyse PDF & Emacs package

on:
  push:
    branches: [main]
    paths:
      - Dockerfile
      - .github/workflows/build.yml
      - src/**
      - test/**
  pull_request:
    branches: [main]
    paths:
      - Dockerfile
      - .github/workflows/build.yml
      - src/**
      - test/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout whyse repo
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build --build-arg GITHUB_CI_BUILD="true" -t whyse .

    - name: Run container to copy build artifacts
      run: |
        container_id=$(docker create whyse)
        docker cp $container_id:/build ./build
        docker rm $container_id

    - name: Upload PDF
      uses: actions/upload-artifact@v4
      with:
        name: whyse-pdf
        path: build/whyse.pdf

    - name: Upload LaTeX final sources (whyse.tex)
      uses: actions/upload-artifact@v4
      with:
        name: whyse-latex-srcs
        path: build/whyse.tex

    - name: Upload latexmk or xelatex (whichever is later) logs (whyse.log)
      uses: actions/upload-artifact@v4
      with:
        name: whyse-latex-logs
        path: build/whyse.log

    - name: Upload Emacs package tarball
      uses: actions/upload-artifact@v4
      with:
        name: whyse-package
        path: build/whyse-*.tar
